# Generated by Django 2.2.3 on 2019-07-17 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='user',
        ),
        migrations.AddField(
            model_name='ad',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Task', verbose_name='Задача'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
    ]
