# Generated by Django 2.2.3 on 2019-07-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Значение'),
        ),
    ]
