# Generated by Django 2.2.3 on 2019-07-12 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190711_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('data', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата')),
                ('views', models.CharField(blank=True, max_length=255, null=True, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ad', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
