# Generated by Django 2.2.3 on 2019-07-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190712_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='uid',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='UID'),
        ),
    ]
