# Generated by Django 2.2.3 on 2019-07-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ad_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='views',
        ),
    ]
