# Generated by Django 2.2.3 on 2019-07-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profile_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ad',
            field=models.ManyToManyField(blank=True, to='api.Ad', verbose_name='Объявления'),
        ),
    ]
